export function renderResolveFontSourceHelper(): string[] {
  return [
    "async function resolveFontSource(src: string): Promise<string> {",
    "  if (!/\\.woff2(?:[?#]|$)/i.test(src)) {",
    "    return src;",
    "  }",
    '  const { default: decompress } = await import("woff2-encoder/decompress");',
    "  const response = await fetch(src);",
    "  if (!response.ok) {",
    '    throw new Error(`Failed to load font "${src}" (${response.status}).`);',
    "  }",
    "  const ttf = await decompress(await response.arrayBuffer());",
    "  const bytes = new Uint8Array(ttf.byteLength);",
    "  bytes.set(ttf);",
    '  return URL.createObjectURL(new Blob([bytes.buffer], { type: "font/ttf" }));',
    "}",
    "",
  ];
}

export function renderThreeLoadFontHelper(): string[] {
  return [
    "async function loadFont(loader: TTFLoader, src: string) {",
    "  const url = await resolveFontSource(src);",
    "  try {",
    "    return await loader.loadAsync(url);",
    "  } finally {",
    "    if (url !== src) {",
    "      URL.revokeObjectURL(url);",
    "    }",
    "  }",
    "}",
    "",
    ...renderResolveFontSourceHelper(),
  ];
}

export function renderReactUseFontHelper(): string[] {
  return [
    "function useFont(src: string) {",
    "  const resource = fontResources.get(src) ?? startFontResource(src);",
    '  if (resource.status === "pending") {',
    "    throw resource.promise;",
    "  }",
    '  if (resource.status === "error") {',
    "    throw resource.error;",
    "  }",
    "  return resource.value;",
    "}",
    "",
    "type FontResource =",
    '  | { status: "pending"; promise: Promise<void> }',
    '  | { status: "success"; value: Awaited<ReturnType<TTFLoader["loadAsync"]>> }',
    '  | { status: "error"; error: unknown };',
    "",
    "const fontResources = new Map<string, FontResource>();",
    "",
    "function startFontResource(src: string): FontResource {",
    "  const resource: FontResource = {",
    '    status: "pending",',
    "    promise: loadFont(src).then(",
    "      (value) => {",
    '        fontResources.set(src, { status: "success", value });',
    "      },",
    "      (error: unknown) => {",
    '        fontResources.set(src, { status: "error", error });',
    "      },",
    "    ),",
    "  };",
    "  fontResources.set(src, resource);",
    "  return resource;",
    "}",
    "",
    "async function loadFont(src: string) {",
    "  const url = await resolveFontSource(src);",
    "  try {",
    "    return await new TTFLoader().loadAsync(url);",
    "  } finally {",
    "    if (url !== src) {",
    "      URL.revokeObjectURL(url);",
    "    }",
    "  }",
    "}",
    "",
    ...renderResolveFontSourceHelper(),
  ];
}
